name: quiz_template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0-1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  web_scraper: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
